const DB_NAME='control-sensores';
const STORE='data';
const initialData={sensors:[],networks:[],assignments:[],pendingSync:false,lastSync:null};
let data=structuredClone(initialData);
let section='sensors';
let db;
let installPrompt;
let editing=null;
let syncing=false;
const selectedSensors=new Set();
const selectedNetworks=new Set();
const selectedAssignments=new Set();
const $=selector=>document.querySelector(selector);
const modal=bootstrap.Modal.getOrCreateInstance('#recordModal');

const config={
  sensors:{title:'Nuevo sensor',button:'Nuevo sensor',columns:['','Sensor','Tipo',''],fields:[['idSensor','ID del sensor','text',true],['tipo','Tipo','select',true],['alias','Alias','text',false]]},
  networks:{title:'Nueva red',button:'Nueva red',columns:['','Red','Propietario','ID',''],fields:[['idRedSensores','ID de la red','text',true],['alias','Alias','text',true],['propietario','Propietario','text',false]]},
  assignments:{title:'Asignar sensor',button:'Nueva asignación',columns:['','Sensor','Red','Ubicación',''],fields:[]}
};

function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function readData(){return new Promise(resolve=>{const request=db.transaction(STORE).objectStore(STORE).get('records');request.onsuccess=()=>{const stored=request.result||{};const migrated={...structuredClone(initialData),...stored};if(!Object.prototype.hasOwnProperty.call(stored,'pendingSync')&&(migrated.sensors.length||migrated.networks.length||migrated.assignments.length))migrated.pendingSync=true;resolve(migrated);};request.onerror=()=>resolve(structuredClone(initialData));});}
function saveData(){return new Promise((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).put(data,'records');request.onsuccess=resolve;request.onerror=()=>reject(request.error);});}
async function saveAndSync(){data.pendingSync=true;await saveData();render();syncData();}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}

function render(){
  $('#sensorCount').textContent=data.sensors.length;$('#networkCount').textContent=data.networks.length;$('#assignmentCount').textContent=data.assignments.length;
  const query=$('#search').value.trim().toLowerCase();
  const rows=data[section].filter(record=>{const values=Object.values(record);if(section==='assignments'){const sensor=data.sensors.find(item=>item.idSensor===record.idSensor);const network=data.networks.find(item=>item.idRedSensores===record.idRedSensores);values.push(sensor?.alias||'',network?.alias||'',network?.propietario||'');}return values.some(value=>String(value).toLowerCase().includes(query));});
  const selectable=true;const selection=section==='sensors'?selectedSensors:section==='networks'?selectedNetworks:selectedAssignments;const idKey=section==='networks'?'idRedSensores':'idSensor';
  $('#tableHead').innerHTML=`<tr>${config[section].columns.map((column,index)=>selectable&&index===0?`<th><input class="select-all" id="selectAll" type="checkbox" aria-label="Seleccionar todos los registros" ${rows.length&&rows.every(row=>selection.has(row[idKey]))?'checked':''}></th>`:`<th>${column}</th>`).join('')}</tr>`;
  $('#tableBody').innerHTML=rows.map(row=>rowHtml(row)).join('');
  $('#empty').hidden=rows.length>0;$('#resultCount').textContent=`${rows.length} ${rows.length===1?'registro':'registros'}`;
  $('#newBtn').textContent=`+ ${config[section].button}`;
  updateSelectionButton();
}

function rowHtml(record){
  if(section==='sensors')return `<tr><td><input class="sensor-check" type="checkbox" data-select="${escapeHtml(record.idSensor)}" aria-label="Seleccionar sensor ${escapeHtml(record.idSensor)}" ${selectedSensors.has(record.idSensor)?'checked':''}></td><td><div class="record-title">${escapeHtml(record.alias||record.idSensor)}</div><div class="record-id">${escapeHtml(record.idSensor)}</div></td><td><span class="pill">${escapeHtml(record.tipo)}</span></td><td class="text-end"><button class="edit-btn" data-edit="${escapeHtml(record.idSensor)}" aria-label="Editar">✎</button><button class="delete-btn" data-delete="${escapeHtml(record.idSensor)}" aria-label="Eliminar">×</button></td></tr>`;
  if(section==='networks')return `<tr><td><input class="network-check" type="checkbox" data-select-network="${escapeHtml(record.idRedSensores)}" aria-label="Seleccionar red ${escapeHtml(record.idRedSensores)}" ${selectedNetworks.has(record.idRedSensores)?'checked':''}></td><td class="record-title">${escapeHtml(record.alias)}</td><td>${escapeHtml(record.propietario||'—')}</td><td class="record-id">${escapeHtml(record.idRedSensores)}</td><td class="text-end"><button class="edit-btn" data-edit="${escapeHtml(record.idRedSensores)}" aria-label="Editar">✎</button><button class="delete-btn" data-delete="${escapeHtml(record.idRedSensores)}" aria-label="Eliminar">×</button></td></tr>`;
  const sensor=data.sensors.find(item=>item.idSensor===record.idSensor);const network=data.networks.find(item=>item.idRedSensores===record.idRedSensores);
  const hasLocation=record.latitud!==undefined&&record.latitud!==''&&record.longitud!==undefined&&record.longitud!=='';
  const location=hasLocation?`${escapeHtml(record.latitud)}, ${escapeHtml(record.longitud)}`:'—';
  return `<tr><td><input class="assignment-check" type="checkbox" data-select-assignment="${escapeHtml(record.idSensor)}" aria-label="Seleccionar asignación ${escapeHtml(record.idSensor)}" ${selectedAssignments.has(record.idSensor)?'checked':''}></td><td><div class="record-title">${escapeHtml(sensor?.alias||record.idSensor)}</div><div class="record-id">${escapeHtml(record.idSensor)}</div></td><td><div class="record-title">${escapeHtml(network?.alias||record.idRedSensores)}</div><div class="record-id">${escapeHtml(record.idRedSensores)}</div></td><td>${location}</td><td class="text-end"><button class="edit-btn" data-edit="${escapeHtml(record.idSensor)}" aria-label="Editar">✎</button><button class="delete-btn" data-delete="${escapeHtml(record.idSensor)}" aria-label="Eliminar">×</button></td></tr>`;
}

function openForm(record=null){
  editing=record?{section,originalId:section==='networks'?record.idRedSensores:record.idSensor}:null;
  $('#modalTitle').textContent=record?`Editar ${section==='sensors'?'sensor':section==='networks'?'red':'asignación'}`:config[section].title;$('#recordForm').reset();
  $('#fields').innerHTML=section==='assignments'?assignmentFields():config[section].fields.map(fieldHtml).join('');
  if(record)Object.entries(record).forEach(([key,value])=>{const input=document.getElementById(key);if(input)input.value=value??'';});
  modal.show();
}
function fieldHtml([id,label,type,required]){
  const requiredMark=required?' *':'';const requiredAttr=required?' required':'';
  if(id==='tipo')return `<div class="mb-3"><label class="form-label" for="${id}">${label}${requiredMark}</label><select class="form-select" id="${id}" name="${id}"${requiredAttr}><option value="">Selecciona…</option><option value="NPKML - Perfil del suelo">NPKML - Perfil del suelo</option><option value="NPK - Nutrientes">NPK - Nutrientes</option><option value="WM - Tensiómetro">WM - Tensiómetro</option><option value="S4 - Humedad del suelo">S4 - Humedad del suelo</option><option value="Tr - Temperatura">Tr - Temperatura</option><option value="Psi - Presión">Psi - Presión</option><option value="FL - Caudal">FL - Caudal</option></select></div>`;
  return `<div class="mb-3"><label class="form-label" for="${id}">${label}${requiredMark}</label><input class="form-control" id="${id}" name="${id}" type="${type}"${requiredAttr}></div>`;
}
function assignmentFields(){return `<div class="mb-3"><label class="form-label" for="idSensor">Sensor *</label><select class="form-select" id="idSensor" name="idSensor" required><option value="">Selecciona…</option>${data.sensors.map(item=>`<option value="${escapeHtml(item.idSensor)}">${escapeHtml(item.alias||item.idSensor)}</option>`).join('')}</select></div><div class="mb-3"><label class="form-label" for="idRedSensores">Red *</label><select class="form-select" id="idRedSensores" name="idRedSensores" required><option value="">Selecciona…</option>${data.networks.map(item=>`<option value="${escapeHtml(item.idRedSensores)}">${escapeHtml(item.alias)}</option>`).join('')}</select></div><div class="row g-3"><div class="col-sm-6"><label class="form-label" for="latitud">Latitud</label><input class="form-control" id="latitud" name="latitud" type="number" step="any" min="-90" max="90" placeholder="19.432608"></div><div class="col-sm-6"><label class="form-label" for="longitud">Longitud</label><input class="form-control" id="longitud" name="longitud" type="number" step="any" min="-180" max="180" placeholder="-99.133209"></div></div>${!data.sensors.length||!data.networks.length?'<div class="alert alert-warning small mt-3 mb-0">Primero registra al menos un sensor y una red.</div>':''}`;}

$('#tabs').addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(!button)return;section=button.dataset.section;document.querySelectorAll('[data-section]').forEach(item=>item.classList.toggle('active',item===button));$('#search').value='';render();});
$('#newBtn').addEventListener('click',openForm);$('#search').addEventListener('input',render);
$('#tableHead').addEventListener('change',event=>{if(event.target.id!=='selectAll')return;const query=$('#search').value.trim().toLowerCase();const selection=section==='sensors'?selectedSensors:section==='networks'?selectedNetworks:selectedAssignments;const key=section==='networks'?'idRedSensores':'idSensor';const visible=data[section].filter(record=>{const values=Object.values(record);if(section==='assignments'){const network=data.networks.find(item=>item.idRedSensores===record.idRedSensores);values.push(network?.alias||'');}return values.some(value=>String(value).toLowerCase().includes(query));});visible.forEach(record=>event.target.checked?selection.add(record[key]):selection.delete(record[key]));render();});
$('#tableBody').addEventListener('change',event=>{const sensorBox=event.target.closest('[data-select]');const networkBox=event.target.closest('[data-select-network]');const assignmentBox=event.target.closest('[data-select-assignment]');const checkbox=sensorBox||networkBox||assignmentBox;if(!checkbox)return;const selection=sensorBox?selectedSensors:networkBox?selectedNetworks:selectedAssignments;const value=sensorBox?sensorBox.dataset.select:networkBox?networkBox.dataset.selectNetwork:assignmentBox.dataset.selectAssignment;checkbox.checked?selection.add(value):selection.delete(value);updateSelectionButton();const selectAll=$('#selectAll');const collection=sensorBox?data.sensors:networkBox?data.networks:data.assignments;const key=networkBox?'idRedSensores':'idSensor';if(selectAll)selectAll.checked=collection.length>0&&collection.every(record=>selection.has(record[key]));});
$('#recordForm').addEventListener('submit',async event=>{event.preventDefault();const record=Object.fromEntries(new FormData(event.currentTarget));const originalId=editing?.section===section?editing.originalId:null;if(section==='sensors'){const oldId=originalId||record.idSensor;data.sensors=data.sensors.filter(item=>item.idSensor!==oldId&&item.idSensor!==record.idSensor);if(oldId!==record.idSensor){data.assignments.forEach(item=>{if(item.idSensor===oldId)item.idSensor=record.idSensor;});if(selectedSensors.delete(oldId))selectedSensors.add(record.idSensor);if(selectedAssignments.delete(oldId))selectedAssignments.add(record.idSensor);}}if(section==='networks'){const oldId=originalId||record.idRedSensores;data.networks=data.networks.filter(item=>item.idRedSensores!==oldId&&item.idRedSensores!==record.idRedSensores);if(oldId!==record.idRedSensores){data.assignments.forEach(item=>{if(item.idRedSensores===oldId)item.idRedSensores=record.idRedSensores;});if(selectedNetworks.delete(oldId))selectedNetworks.add(record.idRedSensores);}}if(section==='assignments'){record.latitud=record.latitud===''?'':Number(record.latitud);record.longitud=record.longitud===''?'':Number(record.longitud);const oldId=originalId||record.idSensor;data.assignments=data.assignments.filter(item=>item.idSensor!==oldId&&item.idSensor!==record.idSensor);if(oldId!==record.idSensor&&selectedAssignments.delete(oldId))selectedAssignments.add(record.idSensor);}data[section].push(record);editing=null;await saveAndSync();modal.hide();render();$('#toastText').textContent=originalId?'Registro actualizado':'Registro guardado en este dispositivo';bootstrap.Toast.getOrCreateInstance('#toast').show();});
$('#tableBody').addEventListener('click',async event=>{const editButton=event.target.closest('[data-edit]');if(editButton){const key=section==='networks'?'idRedSensores':'idSensor';const record=data[section].find(item=>item[key]===editButton.dataset.edit);if(record)openForm(record);return;}const button=event.target.closest('[data-delete]');if(!button||!confirm('¿Eliminar este registro?'))return;const id=button.dataset.delete;const key=section==='networks'?'idRedSensores':'idSensor';data[section]=data[section].filter(item=>item[key]!==id);if(section==='sensors'){selectedSensors.delete(id);selectedAssignments.delete(id);data.assignments=data.assignments.filter(item=>item.idSensor!==id);}if(section==='networks'){selectedNetworks.delete(id);const removed=data.assignments.filter(item=>item.idRedSensores===id);removed.forEach(item=>selectedAssignments.delete(item.idSensor));data.assignments=data.assignments.filter(item=>item.idRedSensores!==id);}if(section==='assignments')selectedAssignments.delete(id);await saveAndSync();render();});
function updateSelectionButton(){const selection=section==='sensors'?selectedSensors:section==='networks'?selectedNetworks:selectedAssignments;const count=selection.size;$('#selectedCount').textContent=count;$('#printQrBtn').hidden=count===0;}
$('#printQrBtn').addEventListener('click',()=>{const collection=data[section];const selection=section==='sensors'?selectedSensors:section==='networks'?selectedNetworks:selectedAssignments;const key=section==='networks'?'idRedSensores':'idSensor';const selected=collection.filter(record=>selection.has(record[key]));if(!selected.length)return;const sheet=$('#printSheet');sheet.innerHTML='';selected.forEach(record=>{const id=record[key];const label=document.createElement('article');label.className='qr-label';const qr=document.createElement('div');const text=document.createElement('strong');text.textContent=id;label.append(qr,text);sheet.append(label);new QRCode(qr,{text:String(id),width:256,height:256,correctLevel:QRCode.CorrectLevel.M});});setTimeout(()=>window.print(),150);});
function connection(){const online=navigator.onLine;const configured=Boolean(window.APP_CONFIG?.API_URL);let text=!online?'● Sin conexión':!configured?'● Guardado local':syncing?'● Sincronizando':data.pendingSync?'● Pendiente sincronizar':'● Sincronizado';$('#connection').textContent=text;$('#connection').classList.toggle('offline',!online||data.pendingSync);}
async function syncData(){const apiUrl=window.APP_CONFIG?.API_URL?.replace(/\/$/,'');if(!apiUrl||!navigator.onLine||syncing)return;syncing=true;connection();try{const options=data.pendingSync?{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({sensors:data.sensors,networks:data.networks,assignments:data.assignments,clientUpdatedAt:new Date().toISOString()})}:{headers:{'Accept':'application/json'}};const response=await fetch(`${apiUrl}/sync`,options);const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`${result.error||`Error ${response.status}`} ${result.code?`(${result.code})`:''}`.trim());const remote=result.data||result;if(Array.isArray(remote.sensors)&&Array.isArray(remote.networks)&&Array.isArray(remote.assignments)){data.sensors=remote.sensors;data.networks=remote.networks;data.assignments=remote.assignments;}data.pendingSync=false;data.lastSync=new Date().toISOString();await saveData();render();}catch(error){console.error('Sincronización pendiente:',error.message);data.pendingSync=true;await saveData();}finally{syncing=false;connection();}}
window.addEventListener('online',()=>{connection();syncData();});window.addEventListener('offline',connection);window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installBtn').hidden=false;});$('#installBtn').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true;});
(async()=>{db=await openDB();data=await readData();connection();render();syncData();setInterval(syncData,30000);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');})();
